### ISSUE TITLE
deposit on zenodo

### ISSUE THREAD

**Issue by thatbudakguy** [direct-phonology/dphon#127]
we can turn on the github auto-deposit feature so that each release gets its own DOI.

**Comment by LinguList** [comment]
if you check our .zenodo json at https://github.com/lingpy/lingpy/ you can also see how you can have zenodo automatically fetch the metadata and cite your work accordingly upon making a new revision!

**Comment by thatbudakguy** [comment]
wow, thank you!! that will be super helpful.
