### ISSUE TITLE
Specify sources of the data

### ISSUE THREAD

**Issue by LinguList** [direct-phonology/dphon#33]
Maybe this is there already, but I could not find it when searching your code: where can I find sources of the data? And where do you describe how you render them? I mean, seeing a file called "Schuessler", I know what to suspect, but where exactly does this come from, what version of Schuessler do you render?

**Comment by thatbudakguy** [comment]
Thanks for this; we definitely need to expand the methodology section in the README. I'm a developer for this project but not really a linguist - I spoke with our linguist and we should have more of an explanation to share in the next few weeks regarding how the sound table is generated from Schuessler. The project is still in early stages at this point.

I've read your paper on sound-class-based alignment and really enjoyed it; hopefully we can apply some of those lessons to this project!

**Comment by thatbudakguy** [comment]
finally got around to adding more information to the methodology section. short answer: we now use the Baxter-Sagart 2014 reconstruction; the JSON files in the data dir of this repo are a more or less direct transformation of the data provided on their website. happy to discuss in more detail if there are still questions!

**Comment by LinguList** [comment]
Thanks! One more question, how do I cite your package? I think, adding an "how-to-cite" information in the readme would be useful (I want to cite it in my work).

**Comment by thatbudakguy** [comment]
added a DOI badge to the README; for now I think you can do:
> Nick Budak, Gian Duri Rominger, and John O'Leary. 2021. direct-phonology/dphon: 2.0.1 (version 2.0.1). Zenodo. doi:10.5281/zenodo.4641277.
